---
- name: Install Matlab Compiler Runtime (MCR) 2021a
  hosts: localhost 
  become: true
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mcr_version: R2021a
    #mcr_install_dir: /mnt/data/mcr/{{ mcr_version }} #change to ebs or efs volume
    mcr_install_dir: /mnt/efs #change to ebs or efs volume
  tasks:

    - name: Create a directory
      file:
        path: /mnt/efs/MATLAB_R2021a
        state: directory
        mode: '0755'


    - name: Update package list
      apt:
        update_cache: yes
  
    - name: Install required packages
      apt:
        name:
          - libglu1
        state: present

    - name: Check if the folder exists
      stat:
        #path: /mnt/data/mcr/R2021a
        path: /mnt/efs

      register: folder_stat_result

    - name: Check if MCR is installed
      stat:
        path: "{{ mcr_install_dir }}/MATLAB_R2021a/mcr_installed"
      register: mcr_install_check

    - name: Download MCR installer #it take a lot of time to download, so I need to find out a solution
      get_url:
        url: "https://ssd.mathworks.com/supportfiles/downloads/R2021a/Release/8/deployment_files/installer/complete/glnxa64/MATLAB_Runtime_R2021a_Update_8_glnxa64.zip"
        dest: "/tmp/mcr_installer.zip"
      when: not mcr_install_check.stat.exists 
      
    - name: Extract MCR installer 
      unarchive:
        src: "/tmp/mcr_installer.zip"
        dest: "{{ mcr_install_dir }}/MATLAB_R2021a"
        remote_src: yes #check if already done pass install
      when: not mcr_install_check.stat.exists

    - name: Install MCR silently
      command: "{{ mcr_install_dir }}/MATLAB_R2021a/install -mode silent -destinationFolder {{ mcr_install_dir }} -agreeToLicense yes"
      args:
        chdir: "{{ mcr_install_dir }}/MATLAB_R2021a"
      when: not mcr_install_check.stat.exists

    - name: Create MCR installation flag file
      file:
        path: "{{ mcr_install_dir }}/MATLAB_R2021a/mcr_installed"
        state: touch
      when: not mcr_install_check.stat.exists

