---
- name: Install and Configure Zabbix Agent 6.4 on Ubuntu 22.04
  hosts: localhost
  become: yes
  gather_facts: no
  vars:
    zabbix_server_ip: "<Zabbix_Server_IP>"
    zabbix_agent_hostname: "<Hostname_Of_Ubuntu_Client>"

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install required package for downloading Zabbix release
      apt:
        name: wget
        state: present

    - name: Download Zabbix 6.4 release package
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu22.04_all.deb"
        dest: "/tmp/zabbix-release_latest+ubuntu22.04_all.deb"

    - name: Install Zabbix 6.4 release package
      command: dpkg -i "/tmp/zabbix-release_latest+ubuntu22.04_all.deb"

    - name: Update APT package cache again
      apt:
        update_cache: yes

    - name: Install zabbix-agent
      apt:
        name: zabbix-agent
        state: present

    - name: Start and enable Zabbix Agent service
      systemd:
        name: zabbix-agent
        enabled: yes
        state: started
